title: Bhanu Prakash 
logo: "/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Senior Frontend Engineer
  <br><br>
  <a href="mailto:"> </a>
  <br>
  <a href="">LinkedIn Profile</a>
  <br>
  <a href="https://www.gihub.com/bhanu-prakashl/">Gihub</a> 
theme: jekyll-theme-minimal
